### ISSUE TITLE
Support for kind/level?

### ISSUE THREAD

**Issue by carstencodes** [chavacava/garif#8]
Hi,

currently, kind and level are specified as [interface](https://github.com/chavacava/garif/blob/b8c73b2037b8509d3b3b215453cc20c0c319a030/models.go#L938).

The [SARIF Spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541085) at this points allows the following values for kind:
- pass
- open
- informational
- notApplicable
- review
- fail

The following values are allowed for level:
- warning
- error
- note
- none

I suggest the following change:

```go
// file: enums.go

package garif;

type ResultKind string

// declare JSON values
const (
   pass ResultKind = "pass"
   open ResultKind = "open"
   informational ResultKind = "informational"
   notApplicable ResultKind = "notApplicable"
   review ResultKind = "review"
   fail ResultKind = "fail"
)

// create public visible constants with a namespace as enums
const (
    ResultKind_Pass ResultKind = pass
    ResultKind_Open ResultKind = open
    ResultKind_Informational ResultKind = informational
    ResultKind_NotApplicable ResultKind = notApplicable
    ResultKind_Review ResultKind = review
    ResultKind_Fail ResultKind = fail
)

type ResultLevel string

// declare JSON values
const (
    warning ResultLevel = "warning"
    error ResultLevel = "error"
    note ResultLevel = "note"
    none ResultLevel = "none"
)

// create public visible constants with a namespace as enums
const (
    ResultLevel_Warning ResultLevel = warning
    ResultLevel_Error ResultLevel = error
    ResultLevel_Note ResultLevel = note
    ResultLevel_None ResultLevel = none
)
```

This way, the types of kind and level could be set to ResultKind and ResultLevel.

What do you think? Should I submit a pull request?

**Comment by chavacava** [comment]
Hi @carstencodes, thanks for filling the issue (and sorry for the late response)
Yes, sure! Your PR will be welcome.
